### ISSUE TITLE
Provide a way to wait for a consumer to enter STARTED status

### ISSUE THREAD

**Issue by kubukoz** [etspaceman/kinesis4cats#130]
Currently, once you start a consumer (KCL), you don't really know when it's running - as a user, as far as I can tell, you have to manually attach a workerStateChangedListener. We should encapsulate this internally and offer a way to wait for that, e.g. for the purpose of testing.

The implementation idea is to create a `SignallingRef` holding the status, and update it in the listener via `cats.effect.std.Dispatcher`. Then have a process that observes changes to the `SignallingRef` and completes when it's `STARTED`. I have some code for this that could be easily adaptable to the library.

**Comment by etspaceman** [comment]
This exists! I have the ability to do this with both Ref and Deferred today:

https://github.com/etspaceman/kinesis4cats/blob/main/kcl/src/main/scala/kinesis4cats/kcl/KCLConsumer.scala#L77
https://github.com/etspaceman/kinesis4cats/blob/main/kcl/src/main/scala/kinesis4cats/kcl/KCLConsumer.scala#L110

**Comment by etspaceman** [comment]
They are also integrated with the KCL Localstack offerings:

https://github.com/etspaceman/kinesis4cats/blob/main/kcl-localstack/src/main/scala/kinesis4cats/kcl/localstack/LocalstackKCLConsumer.scala#L70

**Comment by kubukoz** [comment]
oh really! nice :) Ref and Deferred seems like enough indeed.
