### ISSUE TITLE
Cut new release 🙏🏽 

### ISSUE THREAD

**Issue by gvolpe** [etspaceman/kinesis4cats#362]
There have been a lot of big upgrades recently (including Scala.js v1.16.0) and the latest version 0.0.28 now results in linking errors when using Feral 0.3.0, Smithy4s 0.18.21 and other dependencies.

The issues go away using the latest `0.0.28-39-9ff46a5-SNAPSHOT`. Any plans to cut a new release?

Appreciate the good work, thanks in advance! 🙏🏽

**Comment by kubukoz** [comment]
There was a [0.0.29 in June](https://github.com/etspaceman/kinesis4cats/releases/tag/v0.0.29) and a  [0.0.30 in August](https://github.com/etspaceman/kinesis4cats/releases/tag/v0.0.30), I assume this can be closed now.

We'll probably soon need another bump of Scala.js because of 1.17 😅
